### ISSUE TITLE
Sprites - Accordion expandables

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#10]
The concertina icons aren't appearing correctly on this page (see screen grab)

![image](https://cloud.githubusercontent.com/assets/10434416/6043837/002f1024-ac87-11e4-8be7-af34a3fc5cc8.png)

**Comment by charlottesales** [comment]
it is also happening on this page - http://www.kent.gov.uk/_fostering-beta/who-can-foster/meet-the-children

**Comment by natmunckton** [comment]
Resolved in 42f4d46a9c4bbd47a2fde9e81fb525bcc187745b.

**Comment by CharlesCarnell** [comment]
Now resolved in the Squiz build.
