### ISSUE TITLE
Design - h2 text-transform

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#11]
On publishing content, what do you think about H2 caps in body content? Looks a bit odd? Shall we discuss?

See http://www.kent.gov.uk/_fostering-beta/after-you-have-fostered/_nocache

**Comment by natmunckton** [comment]
Sorry didn't let you know, but H1 and H2 tags are reserved to be used within hero images only. Most headers should be H4s with occasional use of H3s.

Agree we should all look the Squiz site over and decide on the appropriateness of using caps for titles.

**Comment by CharlesCarnell** [comment]
This one resulted in the mega-commit cb927e9e406569d0cf11a43c5e440ab7bec7c0c5, but it should now be resolved and deployed to Squiz.
