### ISSUE TITLE
Success Stories - YouTube Modals

### ISSUE THREAD

**Issue by charlottesales** [kentcc/fostering#13]
Hi, 

just putting the videos in for the success stories and notice that with the button you add the link to the video which then will take you off to youtube. Is there anyway to embed this on the site so the user won't be taken away?

**Comment by CharlesCarnell** [comment]
Success Stories and the Homepage now feature a lightbox-modal for videos, using MagnificPopup.

Resolved in f68fc87c4713a4c495943c80d332c7eb05ace3bc, deployed to Squiz.
