### ISSUE TITLE
success stories main page

### ISSUE THREAD

**Issue by charlottesales** [kentcc/fostering#14]
On the success stories main page, the picture is a link, the button is a link and the heading is a link for each person. The picture and the button link to the video I have put in the metadata but I can't see where to edit the link to the heading? I'm also not sure if this is needed?

**Comment by charlottesales** [comment]
also the internal link doesn't seem to be working. I would like Jordan's story to link to his page as his story is text rather than a video and I have linked it up in the metadata but it just reloads the success stories page when you click the button.

**Comment by CharlesCarnell** [comment]
I'm splitting this issue into two separate ones, this one will remain referencing the item header anchor, the second is referencing the internal / external anchors found at #25.

**Comment by CharlesCarnell** [comment]
Resolved.
