### ISSUE TITLE
Squiz - Landing Pages

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#15]
Is it possible to create a landing page for each of the four top level navs, to automatically pull in the pages which sit at the next level? Users may double click one of the top four headings e.g. Apply, and currently there's no landing page to direct them.

Not urgent for this week.

**Comment by CharlesCarnell** [comment]
@charlottesales has created WYSIWYG landing pages in the meanwhile, further design will be pending @natmunckton.

**Comment by CharlesCarnell** [comment]
This can be re-opened if landing pages are requested again.
