### ISSUE TITLE
Global - Search form placeholder text

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#16]
Please can you change the default text which appears in the search box from 'Search KCC Fostering...' to 'Search kentfostering.co.uk' Thanks.

**Comment by CharlesCarnell** [comment]
Resolved in aa07ca9f87a269f2b915a67ac0283a8638c0126e, Squiz to follow.

**Comment by CharlesCarnell** [comment]
Deployed to Squiz.
