### ISSUE TITLE
request a callback button

### ISSUE THREAD

**Issue by charlottesales** [kentcc/fostering#17]
on this page - http://www.kent.gov.uk/_fostering-beta/about-fostering/success-stories/carers-stories/joshuas-story/_nocache# 

when you click the request a call back button it tries to push the page down and open a small form. 

2 issues - 

1) I don't want this call back button to appear on all pages, but we have to put the H1 in to the page here as otherwise there is an empty space, can we either have this removed on some pages or at least remove the call back button

2) the call back button where it does appear - can this link to this form https://kentcc.firmstep.com/default.aspx/RenderForm/?F.Name=bcBu4dbcECy&HideAll=1 for the moment, I'm working on something smaller but for tomorrow can it link to here? Happy to change this myself if you can let me know where.

**Comment by charlottesales** [comment]
OK just realised that the banner on this page was appearing because of the paint layout applied to the page. I have applied a blank paint layout to the page, which has got rid of the call back button and the header and it has let me left align the content. I think Cat has already logged this, but the heading is disappearing under the top nav. Is there a different paint layout we should use for these pages? 

The points about the where the call back button actually points still stand though and need to point to that achieve form for now. 

Thanks

**Comment by CharlesCarnell** [comment]
Can this issue now be closed, with the Callback Roundel functionality addressed in a separate ticket?

**Comment by CharlesCarnell** [comment]
Closing ticket, refer to #24 for the Callback Roundel functionality.
