### ISSUE TITLE
Content - Images for Success Stories & Meet the Children

### ISSUE THREAD

**Issue by charlottesales** [kentcc/fostering#19]
Hi Nat, 

I know you have just sent us images for the home page for Charlotte, Sophie and Caroline, but we also need images for the circles for the other people on the success stories and meet the children page. 

They don't have videos to take images from so will need to be stock images I guess that kind of match the people? The pictures I need are:

- Jordan - foster child
- Joshua - foster carer
- Julie and Alan - foster carers
- Sandra - foster carer

For meet the children: (maybe like backs of head pics or something?)
- Maya
- Sarah
- Aziz
- Adam and Mark
- Chloe
- Riley

Thanks

**Comment by CharlesCarnell** [comment]
Nat has informed this has been complete, I'm going to close for the immediate time being.
