### ISSUE TITLE
Squiz - News ( linking off-site )

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#20]
All the news stories we currently have on the Fostering site are actually links off to Kent.gov. However, that may not always be the case (we might publish some direct to the fostering site in future) so it'll be a mix. Is it possible on the homepage and 'More news' page for example to be able to link internally and externally? That way, where stories appear on kent.gov we don't need to double publish.

**Comment by CharlesCarnell** [comment]
This feature is no longer requested as according to @CatherineIles.
