### ISSUE TITLE
Design - Social media buttons

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#22]
As per our conversation with Teresa when we met, we need to remove the social media icons from the footer as they don't have any.

**Comment by CharlesCarnell** [comment]
I've spoken with @natmunckton, we've agreed to hide the Social column in the footer and expand the 3 content columns from 3 Foundation columns wide to 4.

Resolved in 2f4deb9aea163808ed0d923df3d3c400434c7096, deployed to Squiz.
