### ISSUE TITLE
order of top headings in the asset map in squiz

### ISSUE THREAD

**Issue by charlottesales** [kentcc/fostering#23]
The order of the assets in the tree have to be backwards for them to appear in the order we want them to appear in the top nav. 

Can we change this?

Not a priority, but confusing :)

**Comment by CharlesCarnell** [comment]
Labelling this as **wontfix** and closing, we can reference this in the future as something to review, but immediate testing of adjusting the float of the navigation items breaks the IE8 layout, making a simple fix unlikely.
