### ISSUE TITLE
Hover state

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#26]
When you're on a page, the top level nav is lime green. But if you're hovering over a top level nav heading, it's also lime green, leading to this:

![image](https://cloud.githubusercontent.com/assets/10434416/6061781/7ea38bb8-ad42-11e4-93ef-7f701c7cc85b.png)

Is this right? Is it confusing?

**Comment by CharlesCarnell** [comment]
We've developed a solution for this interface problem whilst attempting to resolve something different with the navigation, the horizontal centering of the sub-navigation items.

I'll update as we deploy to Squiz.

**Comment by CharlesCarnell** [comment]
This was deployed to Squiz, another solution had been later developed.
