### ISSUE TITLE
Carousel - Controls Position

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#27]
The three little circles relating to each of the promo images on the homepage are sitting half over the images for me (Chrome, 100%) - is this correct? For some reason, I thought they'd be below on the white background.

![image](https://cloud.githubusercontent.com/assets/10434416/6061886/69658084-ad43-11e4-8dc3-a15ba4cdf9e2.png)

**Comment by CharlesCarnell** [comment]
Resolved.
