### ISSUE TITLE
Videos not appearing in modal window

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#31]
I've added a video to the homepage (Sophie's) but it's not opening in a modal window. Instead it's attempting to and then sending users through to view it on YouTube. Please could you have a look? I'd like to show this tomorrow at DMT because I think it's a really nice way of displaying videos.

**Comment by CharlesCarnell** [comment]
I've resolved this by adding the beneath to the anchors.

```
target="_blank"
```
