### ISSUE TITLE
News date

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#32]
There are two date fields in the metadata of News items (near and at the bottom). Which one should we be using? Also, if it's the one at the very bottom, please could you add '2014' in the year field?

**Comment by CharlesCarnell** [comment]
'news.item.date' would be the correct metadata field.

Squiz decided to automatically update the minimum year you could date an article to 2015 when we entered the new year, despite the metadata schema being made prior to 2015. I've set a hard default minimum range of 2014 to counteract this.
