### ISSUE TITLE
Events - Text Alignment

### ISSUE THREAD

**Issue by charlottesales** [kentcc/fostering#34]
on this page - http://www.kent.gov.uk/_fostering-beta/events/_nocache we have added some text above the events listed but the events aren't left aligned to the same point as the text. 

Can we change this? Or can we add a little calendar icon to fill the space?

**Comment by CharlesCarnell** [comment]
@natmunckton and I have updated the design to accommodate the left-aligned texted of the content above the event items, the event items on the event page specifically have been updated to match the same width as used standard across the site.

We'll need to look further into the implications of this, specifically the events page featuring a different design to that which is on the Contact page ( also featuring event items, but with the above content to the items being centered ) at a later point.
