### ISSUE TITLE
Spacing under concertina

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#36]
I'd like to add a couple of bulleted sentences under the concertina on the About fostering page, as related links through to payments and success stories. I've added raw html boxes and a WYSIWYG box to put the text in. However, it's the text is still butting up against the concertina above. I've tried adding <P> tags and <br> tags but it knows what I'm up to and deletes them:

![image](https://cloud.githubusercontent.com/assets/10434416/6111891/2611da50-b084-11e4-91d1-7a44ea48825f.png)

**Comment by CharlesCarnell** [comment]
I've resolved this in the Squiz build.
