### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#37]
On the Contact us page, the heading needs to appear on the image (same as the News page) and there's currently a large gap between the heading and the body text.

Also, perhaps because of the different fonts, styles and colours, the three elements to this page (call, request a call back and upcoming up events) don't quite look like they relate to one another. Is there something we've not done correctly on this page?

**Comment by CharlesCarnell** [comment]
Looking into this immediately.

**Comment by CharlesCarnell** [comment]
The header is now correctly located on the image once again, as per the Generic paint layout.
