### ISSUE TITLE
Events - Events Page only displaying 3 items

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#38]
The homepage displays the three most recent events but when you click on 'All events' you still only see the three most recent. Could all of them appear (future ones only of course)? Thanks.

**Comment by CatherineIles** [comment]
By a similar token, wherever the events feed pulls through to e.g. http://www.kent.gov.uk/_fostering-beta/how-to-apply/contact, it would be good to have a 'See all events' button, as per the homepage.

**Comment by CharlesCarnell** [comment]
This is now resolved in Squiz.
