### ISSUE TITLE
Button length

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#39]
Just adding this for completeness, because you mentioned it last week - I think you were going to look at the length of buttons, particularly o this page http://www.kent.gov.uk/_fostering-beta/about-fostering/success-stories

**Comment by CharlesCarnell** [comment]
I've increased the button width to 213px across the site, this covers all current content used in all buttons where the text was wrapping onto two lines.

I've also created a 'btn-custom-wider' class for cases where we expect longer button text, an example of this would be the Success Stories page. This class increases the width of the buttons to 253px.
