### ISSUE TITLE
Online chat banner not appearing in IE

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#51]
Here's the screen grab Teresa took of the new fostering homepage in IE - the online chat banner wasn't appearing (and she refreshed twice). Could you have a look please?

![kent fostering screen grab](https://cloud.githubusercontent.com/assets/10434416/6246472/5195471e-b761-11e4-9ef5-8cdc2305f942.png)

**Comment by CharlesCarnell** [comment]
Resolved in e2695ebb074df77742a9b5ca8b7e35d5a5590514, and has been tested on the newly created Squiz test platform.

Will close once deployed to Squiz production.

**Comment by CharlesCarnell** [comment]
This has been deployed to Squiz production, and also resolves the same rendering issue with the stock Android browser ( not Chrome ) with the background CSS property shorthand from Clean-CSS.
