### ISSUE TITLE
Verifying http://kentfostering.co.uk

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#53]
Sophie has mentioned, another way to help with the www.kentfostering... and kentfostering... issue is to verify http://kentfostering.co.uk.

Below is the information Google Web Master gives her to do this. Please could you speak with Sophie to action asap?

From: Williams, Sophie - ST TR 
Sent: 18 February 2015 11:27
To: Iles, Catherine - ST TR
Subject: 

  Verification failed for http://kentfostering.co.uk/ using the HTML file method (less than a minute ago). Your verification file was not found.
Verify your ownership of http://kentfostering.co.uk/. Learn more.
Recommended method Alternate methods History
Recommended: HTML file uploadUpload an HTML file to your site.
1. Download this HTML verification file. [googlecabd63bd9e89201f.html]
2. Upload the file to http://kentfostering.co.uk/
3. Confirm successful upload by visiting http://kentfostering.co.uk/googlecabd63bd9e89201f.html in your browser.
4. Click Verify below.
To stay verified, don't remove the HTML file, even after verification succeeds.

Sophie Williams | Senior Digital Services Officer | Media & Public Relations | Kent County Council | Internal: 7200 410439 | External: 03000 410439 | www.kent.gov.uk |  @kent_cc

**Comment by CatherineIles** [comment]
She's also received this - 

https://support.google.com/webmasters/answer/44231?hl=en

You may need to verify ownership of both the www and non-www versions of your domain. Because setting a preferred domain impacts both crawling and indexing, we need to ensure that you own both versions. Typically, both versions point to the same physical location, but this is not always the case. Generally, once you have verified one version of the domain, we can easily verify the other using the original verification method. However, if you've removed the file, meta tag, or DNS record, you'll need to repeat the verification steps.

**Comment by CharlesCarnell** [comment]
Since our non-DNS record resolution has been resolved, I've added the Google verification metatag to our Squiz parsefile.

Sophie has tested this and has confirmed it works.
