### ISSUE TITLE
Page loading times

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#54]
Hi. I loaded Kent Fostering on my phone last night and it took a while for everything to load (at one point it said it had finished loading and there was nothing on the screen!) Looking in Google Webmaster, the page load times are low and there are some suggested amends. Could you review and let me know if there's anything we're able to do to speed it up please. Thanks

https://developers.google.com/speed/pagespeed/insights/?hl=en&utm_source=wmx&utm_campaign=wmx_otherlinks&url=www.kentfostering.co.uk

**Comment by CharlesCarnell** [comment]
I've reviewed all the suggested methods of improving our page speed.

The greatest concern was having users download the large carousel images on mobile devices, unfortunately cursory investigation suggests methods for handling this ( responsive images, lazyLoad, Foundation's Interchange library ) do not gracefully degrade to IE8.

We already compress our images and SVGs, and we compile our CSS & JS. We keep our requests down to a minimum with exceptions only made where necessary ( see Modernizer and Respond ).

What we don't currently offer is gzip compression, I'll have to enquire with our host to see if this can be resolved. I'll reopen if / when I've an update.
