### ISSUE TITLE
Beta site pages appearing

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#55]
I know Charlotte's spoken to you about this already so logging it here for completeness as it's urgent.

We don't want users or search engines to be able to reference the beta fostering site e.g. /how-to-foster  This could potentially be confusing for users, if nothing else.

Please could you rectify? Thanks.

**Comment by CharlesCarnell** [comment]
I had made the changes needed to hide _fostering-beta immediately after Charlotte contacted us, I've attached a robots.txt to the root of the directory.
