### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#7]
Please see screen grab attached. The heading is hidden by the drop down menu and some of the text (under the H2) is centre aligned when I think we agreed it would largely be left aligned, particularly for body content:

![image](https://cloud.githubusercontent.com/assets/10434416/6040725/10676a6e-ac6d-11e4-8316-90276f8bf8df.png)

**Comment by CatherineIles** [comment]
As mentioned above, please could all body content be left aligned? e.g. http://www.kent.gov.uk/_fostering-beta/events

**Comment by CharlesCarnell** [comment]
This can be done in Squiz via the WYSIWYG 'justification', I've attached a screenshot below of the now-updated Events page. This WYSIWYG field is driven via metadata.

![screen shot 2015-02-04 at 14 33 05](https://cloud.githubusercontent.com/assets/10024311/6042240/f520e90c-ac7a-11e4-97bb-aad2b162f89b.png)

**Comment by CatherineIles** [comment]
Can you make it left aligned by default for body text, and then we can centre it if needs be? More likely to be left aligned I think.

**Comment by charlottesales** [comment]
also as an add on I have just tried to left align text on this page - http://www.kent.gov.uk/_fostering-beta/about-fostering/success-stories/items_1/jordans-story/_nocache in the wysiwyg and it doesn't seem to work, so as Cat said, it needs to be default left aligned please.

**Comment by CatherineIles** [comment]
Tried left aligning this one and it won't left me - http://www.kent.gov.uk/_fostering-beta/after-you-have-fostered

**Comment by CharlesCarnell** [comment]
@natmunckton has a resolution for this is in the works, we'll use WYSIWYG to center-align text and default to left-aligning all other text.

The utility class of '.all-text-centered' will be added in cases where WYSIWYG is inappropriate, content such as the Events page will need to be updated with this class or in WYSIWYG to return to their previous state.

**Comment by CharlesCarnell** [comment]
Resolved in 00d962d92b337447c4e1718f153a84d039cd1f67, now deployed to Squiz.
