### ISSUE TITLE
Heading depth

### ISSUE THREAD

**Issue by CatherineIles** [kentcc/fostering#8]
On the How to apply page, there's a large gap underneath the heading, which then means I can't see the content (on mty laptop screen) and I thought the page hadn't loaded. Is there any way to map the gap between header and body content smaller? See screen grab here or 'How to apply' page

![image](https://cloud.githubusercontent.com/assets/10434416/6040889/ca3eff5a-ac6e-11e4-814e-f347e14628f9.png)

**Comment by CharlesCarnell** [comment]
The header is in active re-development to support IE8, the current in-development state is live on the Squiz and static builds.

This should be resolved in our next update.

**Comment by CatherineIles** [comment]
Thanks for this. If you can roll out the next update by lunchtime, so the issue is resolved before my meeting, that would be great.

Thanks

Catherine Iles | Digital Services | Kent County Council | External: 03000 416292 | Internal: 416292 | www.kent.gov.uk<http://www.kent.gov.uk/> | @kent_cc<http://www.twitter.com/kent_cc>

**Comment by natmunckton** [comment]
resolved in 77a2f890d283d78ad20dc2c33ed6d71b1fbb73b1, needs deploying in Squiz @CharlesCarnell

**Comment by CharlesCarnell** [comment]
Deployed to Squiz.

**Comment by CatherineIles** [comment]
Hi. This still looks the same on my screen as when you came in earlier - there's still a large gap at the top which doesn't look consistent with the rest of the page spacing on the page/site, as if there's a heading missing. Please could you keep looking into this. Thanks

**Comment by CharlesCarnell** [comment]
I've resolved this in 07ad6f91eadeefc791bdfd4651a22a0eb1df79ea, the developed resolution to this is at best described as a hack but it resolves the whitespace beneath the header to each page and the content.
